Moved FlowControl class and globals to its own file in uvicorn/protocols/http/
Kludex/uvicorn pull request #1034
Opened 2021-05-10 09:11 UTC by ShahriyarR

As I have spotted most of the parts of `h11_impl.py` and `httptools_impl.py` files are shared. The most notable duplication is FlowControl class and "constants", my suggestion is to move this part to separate file `flow_control.py` and then use it, this will reduce the duplicated code portion.

2021-05-21 16:16 UTC, euri10 requested changes
makes sense, thanks, just need to fix your imports I think
and you can run `scipts/lint` so that CI wont break on that

2021-05-21 19:44 UTC, ShahriyarR commented
@euri10 I have run the scripts/lint as mentioned and pushed the changes.

2021-05-27 07:28 UTC, euri10 approved these changes

2021-05-27 07:28 UTC, euri10 commented
thanks a lot @ShahriyarR !

2021-05-27 07:28 UTC, merged