Remove illogical wording in docs
Kludex/uvicorn pull request #1203
Opened 2021-10-01 12:58 UTC by Andrew-Chen-Wang

I'm not sure if you meant to say reload-includes, and I didn't check the source code, but this just seemed confusing since it says to override the argument you are specifying.

2021-10-02 16:34 UTC, Kludex commented
Hey @Andrew-Chen-Wang , when I read it the first time I also felt confused. But it's actually right, and it makes sense once you read the documentation.

You can check with more details here: https://www.uvicorn.org/settings/#development

In case you have still have a better suggestion on the wording, feel free to open a PR. :)

2021-10-03 02:47 UTC, Andrew-Chen-Wang commented
@Kludex It's definitely the wording. For instance, for `--reload-excludes`:

> These can be overwritten by explicitly including them.

I think it would make sense if it simply says: `These defaults can be overwritten by including them in --reload-include`.

So the changes are "These defaults" (so I know "these" points to the defaults and not the flag arguments itself if I specify the reload-exclude flag) and "--reload-include" instead of `reload-excludes` or something related. I'd much rather see the CLI flag explicitly.

2021-10-03 13:25 UTC, Kludex commented
I see, you're right.

2021-10-03 14:17 UTC, Andrew-Chen-Wang commented
Thanks for understanding; my speaking skills are worse :P I've changed main.py; for the development docs, do I change this file directly: https://github.com/encode/uvicorn/blob/master/docs/settings.md

2021-10-03 14:18 UTC, Kludex commented
Nop, you should run `./scripts/lint`. It will format the documentation for you!

2021-10-03 14:22 UTC, Andrew-Chen-Wang commented
Ah sorry, I meant I changed main.py for the docs/index.md, but should I change the docs/settings.md file directly for the other wording?

2021-10-03 14:23 UTC, Kludex commented
Oh! I forgot about this file. Go ahead, please.

2021-10-03 14:29 UTC, Andrew-Chen-Wang commented
👍 thanks @Kludex

2021-10-03 14:37 UTC, Kludex commented
No! Thank you! :tada:

2021-10-03 14:39 UTC, Kludex requested changes
I've just noticed that the documentation uses quotes to reference to other commands, would you mind applying those? :pray:

2021-10-03 14:39 UTC, Kludex commented on docs/settings.md
> +* `--reload-include <glob-pattern>` - Specify a glob pattern to match files or directories which will be watched. May be used multiple times. By default the following patterns are included: `*.py`. T
```suggestion
* `--reload-include <glob-pattern>` - Specify a glob pattern to match files or directories which will be watched. May be used multiple times. By default, the following patterns are included: `*.py`. These defaults can be overwritten by including them in `--reload-exclude`.
```

2021-10-03 14:39 UTC, Kludex commented on docs/settings.md
> +* `--reload-exclude <glob-pattern>` - Specify a glob pattern to match files or directories which will excluded from watching. May be used multiple times. By default the following patterns are exclude
```suggestion
* `--reload-exclude <glob-pattern>` - Specify a glob pattern to match files or directories which will excluded from watching. May be used multiple times. By default, the following patterns are excluded: `.*, .py[cod], .sw.*, ~*`. These defaults can be overwritten by including them in `--reload-include`.
```

2021-10-03 14:39 UTC, Kludex commented on uvicorn/main.py
> +    "'.*, .py[cod], .sw.*, ~*' by default; the defaults can be overridden "
```suggestion
    "'.*, .py[cod], .sw.*, ~*' by default; these defaults can be overridden "
```

2021-10-03 14:53 UTC, Kludex approved these changes

2021-10-03 15:43 UTC, Kludex commented
Thanks @Andrew-Chen-Wang ! :tada:

2021-10-03 15:44 UTC, merged