Add contributing page to the docs (#1197)
Kludex/uvicorn pull request #1224
Opened 2021-10-20 13:58 UTC by humrochagf

A small change to the testing script was added to follow the same testing capabilities from other encode projects, like the ability to run a single testing file or test during development.

EDIT by @Kludex : Closes #1197

2021-10-20 14:01 UTC, humrochagf commented
Just the releasing part that I'm not quite sure it's 100% accurate

2021-10-21 06:56 UTC, Kludex requested changes
Thanks for the PR @humrochagf ! :tada:

2021-10-21 06:56 UTC, Kludex commented on docs/contributing.md
> +- **A version bump**: see `__version__.py`.
```suggestion
- **A version bump**: see `__init__.py`.
```

2021-10-21 06:56 UTC, Kludex commented on docs/contributing.md
> +- [Implementing new features and fixing bugs](https://github.com/encode/uvicorn/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)
We actually don't use the "good first issue" label, maybe "help wanted"?
```suggestion
- [Implementing new features and fixing bugs](https://github.com/encode/uvicorn/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22)
```

2021-10-21 06:56 UTC, Kludex commented on docs/contributing.md
> +
```suggestion
```

2021-10-21 06:56 UTC, Kludex commented on docs/contributing.md
> +- Does the issue exist with `Client`, `AsyncClient`, or both?
```suggestion
```

2021-11-23 14:25 UTC, humrochagf commented
Is there anything missing for this one?

2021-11-23 14:53 UTC, euri10 approved these changes
looks good to me, I let @Kludex push the final go !

2021-11-23 15:22 UTC, Kludex approved these changes
Thanks again @humrochagf ! :smile:

2021-11-23 15:22 UTC, merged