Load more than one ca_cert
Kludex/uvicorn pull request #1255
Opened 2021-11-19 11:37 UTC by brussee

`ca_certs` is plural, but currently does not accept a list of CA certificate paths.

2021-11-19 11:46 UTC, euri10 commented
I'm dubious about this PR, I'm no SSL expert though but this seems like this link explains it quite well : pass a directory containing your CAs : https://docs.python.org/3/library/ssl.html#ssl.SSLContext.load_verify_locations
Feel free to reopen if that's not the case

2021-11-19 11:56 UTC, brussee commented
You are referring to the 2nd argument of `load_verify_locations` but the current implementation gives only the 1st positional argument:
> The cafile string, if present, is the path to a file of concatenated CA certificates in PEM format.

My PR proposes to allow a list, such that instead of concatenating all CA certs beforehand, you can provide a list of certificate files in different locations. This is arguably more flexible than requiring all of the files to be in a single directory.

@euri10 please re-open if you agree/want to re-consider

2021-11-19 11:58 UTC, euri10 commented
Happy to reconsider then effectively, but: 
1. add tests
2. change the positional only arg we currently have to kwargs so that we're clear on what location we use

2021-11-19 12:20 UTC, brussee commented
@euri10 done

2021-11-19 12:37 UTC, brussee commented
@euri10 updated formatting to make the linter happy

2021-11-19 13:44 UTC, brussee commented
@euri10 Would you like me to squash before merging?

2021-11-19 13:45 UTC, euri10 commented
No need it's automatic on the repo iirc

2021-11-20 18:31 UTC, euri10 requested changes

2021-11-20 18:31 UTC, euri10 commented on tests/test_config.py
> +def test_ssl_config_ca_cert(
appart from the name what is the difference between those 2 tests ?

2021-11-20 18:31 UTC, euri10 commented on tests/test_config.py
> +    assert len(config_ssl.get_ca_certs()) == 1
This doesn't test the added feature ie more than one path/str or I'm missing something ?
Adding a cert in `test_ssl` would certainly be the place you'd do that

2022-07-07 19:48 UTC, Kludex commented
@brussee Are you still interested on this PR? If so, would you mind checking @euri10 's comments? 🙏

2022-07-29 19:40 UTC, brussee commented
I switched from the approach in this PR to creating and injecting a fully configured SSLContext directly.
Instead of maintaining code that wraps the SSLContext class like now, the alternative seems like a more maintainable approach.

2022-09-11 12:56 UTC, closed without merging