allow configurable websocket per-message-deflate setting
Kludex/uvicorn pull request #1300
Opened 2021-12-25 17:10 UTC by cfal

closes #1298 

please take a look, thanks!

2021-12-26 13:20 UTC, euri10 approved these changes
this looks good thanks @cfal !

2021-12-26 13:23 UTC, euri10 requested changes
you'll just need to run `scripts/lint` I think to please the CI !

2021-12-26 16:03 UTC, cfal commented
> you'll just need to run `scripts/lint` I think to please the CI !

got it, thanks!

2021-12-29 15:21 UTC, euri10 approved these changes

2021-12-29 15:21 UTC, merged