Fix `x_forwarded_proto` for websockets in `proxy_headers.py`
Kludex/uvicorn pull request #1934
Opened 2023-04-09 02:10 UTC by 1997cui

As discussed in #1933, the upstream proxies (i.e., Caddy) will always pass `http` or `https` in `x_forwarded_proto`, even if it is a WebSocket Upgrade request. However, storing the `http` or `https` in a WebSocket scope is not correct. In this pull request, I added some if statements to solve this issue.

I know there are no unit tests, because I don't know how to write, and help wanted.

2023-04-11 10:44 UTC, aminalaee commented on uvicorn/middleware/proxy_headers.py
> +                        ] = x_forwarded_proto.strip()  # type: ignore[index]
Maybe a personal preference but anyway the `.strip()` is duplicated. :shrug: 

```py
x_forwarded_proto = headers[b"x-forwarded-proto"].decode("latin1").strip()
if scope["type"] == "websocket":
    scope["scheme"] = "wss" if x_forwarded_proto == "https" else "ws"
else:
    scope["scheme"] = x_forwarded_proto
```

2023-06-19 08:07 UTC, Kludex requested changes
I couldn't find any reference online that would mention this is needed. Do you have any reference from a proxy server, or any reference at all that sends `"wss"` or `"ws"` on `X-Forwarded-Proto`?

In case you have a reference, and it's not ambiguous, then please apply @aminalaee 's suggestion, and add a test.

2023-06-19 08:08 UTC, Kludex commented
> I know there are no unit tests, because I don't know how to write, and help wanted.

I can help on it, in case you provide what I asked above. 🙏

2023-06-19 08:10 UTC, Kludex commented
I'm sorry. I got what you are doing. 👍

2023-06-19 08:18 UTC, Kludex commented
I can't force push changes to this branch.

2023-06-19 08:38 UTC, 1997cui commented
Just tried to give you permission:

[Invite link](https://github.com/1997cui/uvicorn/invitations)

2023-06-19 08:51 UTC, Kludex commented
> Just tried to give you permission:
> 
> [Invite link](https://github.com/1997cui/uvicorn/invitations)

It's much easier if you create a new PR not from your main branch... 🤷‍♂️

2023-06-19 09:14 UTC, 1997cui commented
> > Just tried to give you permission:
> > [Invite link](https://github.com/1997cui/uvicorn/invitations)
> 
> It's much easier if you create a new PR not from your main branch... man_shrugging

Created a new one in #2011

2023-06-19 09:14 UTC, closed without merging