add log configuration file to docs
Kludex/uvicorn pull request #2031
Opened 2023-07-07 04:08 UTC by ruckshan-ratnam

# Summary

Wanted to throw my hat into issue #491. I went ahead and added a section on logging with an example logging configuration yaml file as well as ways to use the logging file programmatically and via the command line in the docs.

# Checklist

- [x] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
  - since this is a document change, I do not think this applies? 
- [x] I've updated the documentation accordingly.

2023-07-21 00:10 UTC, guibordignon requested changes

2023-07-21 00:10 UTC, guibordignon commented on docs/index.md
> +You can also customize your logs using a configuration file written in YAML or JSON format. You can find more info on creating these files from the official Python documentation found [here](https://
```suggestion
You can also customize your logs using a configuration file written in YAML or JSON format. 

Find more information on creating these files in the [official Python documentation](https://docs.python.org/3/howto/logging.html#configuring-logging).
```

2023-07-21 00:10 UTC, guibordignon commented on docs/index.md
> +Below I have provided an example of a log file written in YAML that will get you started.
```suggestion
Here's an example of a log file written in YAML that will get you started.
```

2023-07-21 00:10 UTC, guibordignon commented on docs/index.md
> +After you have configured the logging file above you can use it progromatically as seen below
```suggestion
After you have configured the logging file above, you can use it programmatically as seen below:
```

2023-07-21 00:10 UTC, guibordignon commented on docs/index.md
> +> **_NOTE:_**  Using Uvicorn's formatter gives us access to the terminal colors and proper formatting
```suggestion
> **_NOTE:_**  Using Uvicorn's formatter gives us access to the terminal colors and proper formatting.
```

2023-07-21 00:10 UTC, guibordignon commented on docs/index.md
> +Or you can use via command line like below
```suggestion
Or you can use via command line like below:
```

2023-07-21 00:10 UTC, guibordignon commented on docs/index.md
> +<!-- :cli_usage: -->
```suggestion
```

2023-07-21 00:22 UTC, ruckshan-ratnam commented
Thanks for the suggestions @guibordignon

2023-07-21 22:13 UTC, guibordignon approved these changes

2024-07-10 07:09 UTC, Aruelius approved these changes

2026-04-21 13:11 UTC, Kludex commented
I've merged a similar PR some time ago, the new page is here: https://uvicorn.dev/concepts/logging

Sorry the delay on the review here.

2026-04-21 13:11 UTC, closed without merging