Bump httpx
Kludex/uvicorn pull request #2288
Opened 2024-03-25 20:52 UTC by dcermak

# Summary

httpx version 0.27.0 deprecated the `app=` shortcut, which makes uvicorn's testsuite now fail in openSUSE. This PR fixes the tests for httpx 0.27.0 by relying on `ASGITransport(app=app)` instead.

# Checklist

- [x] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.

2024-03-26 14:39 UTC, dcermak commented
Type checking currently fails due to https://github.com/encode/httpx/pull/3109 not being in the httpx 0.27 release

2024-03-26 16:47 UTC, Kludex requested changes
You can add `# type: ignore` on those.

2024-03-26 16:47 UTC, Kludex commented on tests/middleware/test_message_logger.py
> +        async with httpx.AsyncClient(transport=transport, base_url="http://testserver") as client:
Can we apply this style on the other tests, please? i.e. `transport` in a single line, and then `transport=transport`.

2024-04-04 15:15 UTC, dcermak commented
> You can add `# type: ignore` on those.

Done. Should I add FIXMEs to remove this once the next httpx release is out?

2024-04-13 08:17 UTC, Kludex commented
> > You can add `# type: ignore` on those.
> 
> Done. Should I add FIXMEs to remove this once the next httpx release is out?

No. We already error on unused `type: ignore`s.

2024-04-13 08:18 UTC, Kludex approved these changes

2024-04-13 08:19 UTC, Kludex commented
@dcermak Thanks! 🙏

2024-04-13 08:19 UTC, merged