Raise uvloop version to 0.13.*
Kludex/uvicorn pull request #406
Opened 2019-08-14 07:37 UTC by jlaine

uvloop 0.13.0 was released a few hours ago. Although it's not *needed* for uvicorn, it's nice for projects which do require the updated uvloop (for instance for better UDP performance) in the same virtualenv.

An alternative would be to loosen the versioning scheme.

2019-08-16 06:39 UTC, jlaine commented
I'm not sure whether the CI breakage was actually caused by the PR or not

2019-08-20 15:34 UTC, tomchristie commented
Want to merge master in, and see where we're at?

2019-08-20 17:19 UTC, jlaine commented
Somehow this broke Python 3.7-dev's tests

2019-08-20 17:59 UTC, tomchristie commented
Lovely 😐

2019-08-20 18:00 UTC, tomchristie commented
Will try to dig tomoz 🙃

2019-08-21 09:05 UTC, jlaine commented
I had a look and it looks like the failing test is not the root cause. If I print `caplog.records` at the very start of `test_request_logging` it already contains the warning about a pending task being destroyed.

Adding `caplog.records.clear()` at the top of `test_request_logging` works around the problem but it would be nice to know why we have this destroyed pending task.

2019-08-21 11:54 UTC, tomchristie commented
> the WSGI middleware tests, most likely the ones which trigger an exception

That might be a good call - yup.

2019-08-27 10:31 UTC, tomchristie commented
> UPDATE: the failure originates in the WSGI middleware tests, most likely the ones which trigger an exception

Do you have a good way of isolating and reproducing that? I'd like to have a dig into resolving it.

2019-08-27 14:56 UTC, jlaine commented
I can reproduce the issue locally (Debian / Python 3.7 / uvloop 0.13.0) by running the full test suite: the wsgi middleware tests pass, but they produce a warning which trips up the `test_request_logging` test, which fails in the same way as:

https://travis-ci.org/encode/uvicorn/jobs/574436943#L300

2019-09-04 11:22 UTC, jlaine commented
Yay, #418 indeed fixed CI!

2019-09-04 11:41 UTC, lovelydinosaur requested changes
I think we ought to switch to `0.*` instead.
I can't really see uvloop breaking their existing (very very minimal) API contract, without a 1.x version bump, so that seems like the best tradeoff to me, here.

2019-09-04 11:41 UTC, tomchristie commented on setup.py
> -    "uvloop==0.12.* ;" + env_marker,
Let's go to `0.*` instead.

2019-09-04 11:49 UTC, jlaine commented
It might be nice to have a Travis cron job to run CI periodically regardless of whether there are new commits to uvicorn, to catch an unexpected regression?

https://docs.travis-ci.com/user/cron-jobs/

2019-09-04 11:52 UTC, tomchristie commented
Interesting possibility, yeah.
Not sure how we'd work that into a notification of some kind, tho? (So that it's visible when it starts failing.)

2019-09-04 11:56 UTC, jlaine commented
uvloop does periodic CI runs using a cron, you can see the builds marked as "CRON":

https://travis-ci.org/MagicStack/uvloop/builds

Not sure if @1st1 receives notifications when the build fails?

2019-09-04 12:30 UTC, lovelydinosaur approved these changes

2019-09-04 12:30 UTC, merged

2019-09-04 12:30 UTC, tomchristie commented
Let's get this in.
Thanks!