Version 0.13.1
Kludex/uvicorn pull request #880
Opened 2020-12-09 17:17 UTC by florimondmanca

## 0.13.1 - 2020-12-10

### Fixed

- Prevent exceptions when the ASGI application rejects a connection during the WebSocket handshake, when running on both `--ws wsproto` or `--ws websockets`. (Pull #704)
- Ensure connection `scope` doesn't leak in logs when using JSON log formatters. (Pull #859)

2020-12-09 17:18 UTC, florimondmanca commented
@euri10 Hi, confirm we're okay releasing #859 in this version?

2020-12-09 17:21 UTC, euri10 commented
Looks good yes 😉

2020-12-09 18:30 UTC, euri10 commented
Maybe take a look at https://github.com/encode/uvicorn/pull/881 before @florimondmanca ! ;)

2020-12-12 10:28 UTC, euri10 requested changes

2020-12-12 10:28 UTC, euri10 commented on CHANGELOG.md
> +- Prevent exceptions when the ASGI application rejects a connection during the WebSocket handshake, when running on both `--ws wsproto` or `--ws websockets`. (Pull #704)
```suggestion
- Prevent exceptions when the ASGI application rejects a connection during the WebSocket handshake, when running on both `--ws wsproto` or `--ws websockets`. (Pull #704 and #881)
```

2020-12-12 10:28 UTC, euri10 commented on CHANGELOG.md
> +## 0.13.1 - 2020-12-10
```suggestion
## 0.13.1 - 2020-12-12
```

2020-12-12 10:28 UTC, euri10 commented on CHANGELOG.md
> +- Ensure connection `scope` doesn't leak in logs when using JSON log formatters. (Pull #859)
```suggestion
- Ensure connection `scope` doesn't leak in logs when using JSON log formatters. (Pull #859 and #884)
```

2020-12-12 10:28 UTC, euri10 commented on CHANGELOG.md
> +- Ensure connection `scope` doesn't leak in logs when using JSON log formatters. (Pull #859)
in case #884 gets merged, but we should do something

2020-12-12 11:14 UTC, euri10 approved these changes
Looks good to me, hopefully >)_

2020-12-12 11:55 UTC, merged

2020-12-12 11:58 UTC, florimondmanca commented
> hopefully

I think one area where we could do some work in Uvicorn is make it so we have to be less "hopeful" when pushing new releases. 😄 I'm seeing two precise areas: A/ generalizing type annotations (_including_ in the test suite) so we can catch some more bugs or make sure implementations are as type-safe as possible (always good), and B/ going over the test suite to clean anything up or add small cases that are missing. (Refs #102)

2020-12-12 12:13 UTC, euri10 commented
cant agree more to that, just lacking time atm !